### ISSUE TITLE
Profiler "only ticks over" might be working incorrectly

### ISSUE THREAD

**Issue by BondarenkoArtur** [lucko/spark#411]
### Description

I was following guide https://spark.lucko.me/docs/guides/Finding-lag-spikes

And was trying to find all ticks that making tps < 20. 
My understanding that ticks longer than 50ms should be problematic to tps, so I run profiler with next command:
`/spark profiler --only-ticks-over 50`

Result that I got said that
The profiler was running for 4m 50s (5790 ticks). 2919 ticks exceeded the 'only ticks over' threshold.
Which is ~50% of all ticks.
But at the same time in top left corner it shows 
TPS 20.00 1m
MSPT 0.676 min | 4.43 med | 8.39 95%ile | 143 max
So if I read it correctly I should have for sure less than 5% of my ticks over threshold, if like 95% around 8ms (which is less than 50 that I set).

Versions and other logs are available in report.
Spark 1.10.58-fabric
https://spark.lucko.me/aDdpCEu3HR

### Reproduction Steps

1. `/spark profiler --only-ticks-over 50` 
2. `/spark profiler stop`

### Expected Behaviour

I expect to get less items in log

### Platform Information

* Minecraft Version: 1.20.4
* Platform Type: server
* Platform Brand: Fabric
* Platform Version: 0.15.11

### Spark Version

1.10.58-fabric

### Logs and Configs

https://spark.lucko.me/aDdpCEu3HR

### Extra Details

Additional log, same issue
https://spark.lucko.me/d7SPNUKIUO

**Comment by Miasmusa** [comment]
Sorry if I'm misunderstanding something, but I seem to be still getting this issue on 1.21.1 with spark 1.10.109. I'm having extreme mspt spikes (600 ms+) but the profiler displays almost every tick, despite running it with `--only-ticks-over 500`. I'd really appreciate any help with this, as I'm struggling to find the tps issue and spark is otherwise extraordinarily helpful.
Here's the profile: https://spark.lucko.me/oaU1R6K5lm

**Comment by BondarenkoArtur** [comment]
@Miasmusa I would suggest cutting separate ticket and mentioning this one in it to gain visibility.
