### ISSUE TITLE
Tick Durations not showing on 1.12 / 1.8 servers

### ISSUE THREAD

**Issue by i0xHeX** [lucko/spark#53]
![image](https://user-images.githubusercontent.com/33582973/82122232-f175ac00-979a-11ea-8939-38443a7f052c.png)

Paper b1618 (1.12.2)
Spark b133

I can confirm it shows at least on Paper 1.15.2 
(don't know about 1.13-1.14)

**Comment by astei** [comment]
The relevant Paper patch was only introduced [in the late 1.13.2 era](https://github.com/PaperMC/Paper/blob/ver/1.13.2/Spigot-API-Patches/0180-Server-Tick-Events.patch). Tracking MSPT without an explicit tick start/tick end patch is difficult (since without NMS or mixins, we can only use the Bukkit scheduler, which is not accurate).

If you are willing to modify your server JAR, [here's a patch that we made against Paper 1.12.2 for our fork](https://gist.github.com/astei/ba079e508e712fe8dd0574109784233b).

**Comment by i0xHeX** [comment]
I think I may close it as problem is solved, thanks @astei for tip & patch!
